title: ⏰ VIS Conference Deadlines
description: Countdowns to top VIS conference deadlines
author: Andrea Bianchi

baseurl: '/vis-deadlines'
domain: 'sleepydui.github.io'

twitter_hashtag: vis-deadlines
github_username: makinteractlab
github_repo: vis-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
