title: ⏰ VIS Conference Deadlines
description: Countdowns to top VIS conference deadlines
author: VisRoad

baseurl: '/vis-deadlines'
domain: 'vis-deadlines'

twitter_hashtag: vis-deadlines
github_username: vis-deadlines
github_repo: vis-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
